spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/blog
    username: postgres
    password: yuweibin
  jpa:
    hibernate:
      ddl-auto: update


global:
  secret: adkfjsdhfdsl
  duration: 30D

